name: Project2 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile ftlmgr
        run: gcc -std=c11 -Wall -Wextra -o a.out ftlmgr.c fdevicedriver.c

      - name: Test create flash file
        run: |
          ./a.out c flashmemory 2
          test -f flashmemory || (echo "Flash file not created" && exit 1)
          expected=$((2*8*(512+16)))
          actual=$(stat -c%s flashmemory)
          [ "$actual" -eq "$expected" ] || (echo "Size mismatch: expected $expected, got $actual" && exit 1)

      - name: Test page write and read
        run: |
          # Test case 1: ppn 1, sector data "hello", spare data "100"
          ./a.out w flashmemory 1 "hello" "100"
          output=$(./a.out r flashmemory 1)
          expected="hello 100"
          if [ "$output" != "$expected" ]; then
            echo "Test case 1 failed: expected '$expected', got '$output'"
            exit 1
          fi

          # Test case 2: ppn 2, sector data "abcde", spare data "0"
          ./a.out w flashmemory 2 "abcde" "0"
          output=$(./a.out r flashmemory 2)
          expected="abcde 0"
          if [ "$output" != "$expected" ]; then
            echo "Test case 2 failed: expected '$expected', got '$output'"
            exit 1
          fi

          # Test case 3: ppn 3, sector data "data", spare data "999"
          ./a.out w flashmemory 3 "data" "999"
          output=$(./a.out r flashmemory 3)
          expected="data 999"
          if [ "$output" != "$expected" ]; then
            echo "Test case 3 failed: expected '$expected', got '$output'"
            exit 1
          fi

          # Test case 4: ppn 4, sector data "longerTestString", spare data "123456"
          ./a.out w flashmemory 4 "longerTestString" "123456"
          output=$(./a.out r flashmemory 4)
          expected="longerTestString 123456"
          if [ "$output" != "$expected" ]; then
            echo "Test case 4 failed: expected '$expected', got '$output'"
            exit 1
          fi

      - name: Test block erase
        run: |
          # Write to ppn=8 in block 1
          ./a.out w flashmemory 8 "data8" "20"
          # Read ppn=8 to confirm
          output=$(./a.out r flashmemory 8)
          expected="data8 20"
          if [ "$output" != "$expected" ]; then
            echo "Write to ppn=8 failed: expected '$expected', got '$output'"
            exit 1
          fi
          # Erase block 0
          ./a.out e flashmemory 0
          # 읽지 않은(또는 지워진) 영역은 0xFF로 초기화되어 있어, 읽을 경우 " -1" 결과가 출력되어야 함
          output=$(./a.out r flashmemory 0)
          expected=""
          if [ "$output" != "$expected" ]; then
            echo "After erase, ppn=0 not erased: expected '$expected', got '$output'"
            exit 1
          fi
          # ppn=8은 블록 1에 해당하므로 영향이 없어야 함
          output=$(./a.out r flashmemory 8)
          expected="data8 20"
          if [ "$output" != "$expected" ]; then
            echo "After erase, ppn=8 changed: expected '$expected', got '$output'"
            exit 1
          fi
          # 블록 0의 다른 페이지(ppn=1)도 확인
          output=$(./a.out r flashmemory 1)
          expected=""
          if [ "$output" != "$expected" ]; then
            echo "After erase, ppn=1 not erased: expected '$expected', got '$output'"
            exit 1
          fi